### ISSUE TITLE
Must have:

### ISSUE THREAD

**Issue by mohammadali-bacha** [mohammadali-bacha/THP-2.0#15]
- [x] Staging
   - [x] Prod
   - [ ] Auto deploy master on Staging
   - [x] Deploy should run migrations

**Each should have:**

   - [x] Postgres

Important: Do not configure your term to be able to talk to heroku.
**Todo**

   - [x] Create an heroku pipeline
   - [x] Create the staging app
   - [x] Create the prod app
   - [x] Add postgres on both
   - [x] Add a Procfile to the App
   - [x] Configure ruby version to 2.5.1 (.ruby-version) and add it to the Gemfile (ruby File.read('./.ruby-version'))
   - [x] Configure ruby gemset so you know your gems are for this app only (.ruby-gemset)
   - [x] Add a release step in your procfile to run the migrations (https://devcenter.heroku.com/articles/release-phase)
   - [ ] Configure heroku so it auto deploys master on staging.
   - [ ] Deploy it
   - [ ] Promote to production
   - [ ] Check that everything is right by running a console in Staging and creating a Lesson with it.
