### ISSUE TITLE
Create the App

### ISSUE THREAD

**Issue by mohammadali-bacha** [mohammadali-bacha/THP-2.0#2]
**Why ?**

Creating the app, "the right way" will help the process as changing the default after is a bit tedious/difficult in rails.

**Must have**: 
- [x] Postgresql 
- [x] No front 
- [x] No Tests framework to an issue named Create the App a day ago

**Todo**

- [x] Create the app
- [x] Read through the rails new --help documentation

**Reading list**

*What is rails api mode*

   - [x] http://guides.rubyonrails.org/api_app.html

*What is a middleware*

   - [x] http://railscasts.com/episodes/151-rack-middleware
   - [ ] http://guides.rubyonrails.org/rails_on_rack.html#action-dispatcher-middleware-stack
